# Generated by Django 4.1.6 on 2023-04-06 22:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['date', 'time']},
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='hour',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='order',
        ),
        migrations.AddField(
            model_name='appointment',
            name='cause',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('proposed', 'Proposed')], default='requested', max_length=10),
        ),
    ]
