# Generated by Django 4.1.6 on 2023-04-07 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_appointment_options_remove_appointment_hour_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repport',
            old_name='repportRemarque',
            new_name='remarques',
        ),
    ]
