# Generated by Django 4.1.6 on 2023-04-08 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_doctor_id_patient_id_receptionist_id_and_more'),
        ('main', '0004_alter_medicalrecord_patient_alter_ordonnance_repport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.patient'),
        ),
    ]
