# Generated by Django 4.1.6 on 2023-04-08 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_medicalrecord_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='repport',
            old_name='MedicalRecord',
            new_name='medical_record',
        ),
    ]
