# Generated by Django 4.1.6 on 2023-04-08 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rename_medicalrecord_repport_medical_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='repport',
            name='diagnostics',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='repport',
            name='medical_history',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='repport',
            name='ongoing_treatment',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('city', models.CharField(max_length=20)),
                ('notes', models.CharField(max_length=500)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.repport')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('notes', models.CharField(max_length=500)),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.prescription')),
            ],
        ),
    ]
