# Generated by Django 4.1.6 on 2023-04-09 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_repport_diagnostics_repport_medical_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='report',
        ),
        migrations.DeleteModel(
            name='Medication',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
