# Generated by Django 4.1.6 on 2023-04-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_ordonnance_repport_repport_ordonnance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repport',
            name='ordonnance',
        ),
        migrations.AddField(
            model_name='repport',
            name='medications',
            field=models.CharField(default='a', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repport',
            name='notes',
            field=models.CharField(default='aaaaaa', max_length=500),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Ordonnance',
        ),
    ]
